### ISSUE TITLE
Failing to install - Python 3 Error

### ISSUE THREAD

**Issue by felix-dolderer** [sugoidesune/nuxt-scss-to-js#1]
I got an error when trying to install via `npm install nuxt-scss-to-js` (in an existing nuxt project, as well as in a new, empty project)
I did not test if installing via yarn works.

I get the following output from npm: (in the error-message I replaced paths which include the devicename/username, otherwise it is unchanged)

From the output I suspect, there is an incompatibility with Python 3.9 (`Python 3.9.2` to be exact)

```
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path {path to my project}\testing-stuff\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe {path to my project}\testing-stuff\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   '{path to my project}\\testing-stuff\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node@15.9.0 | win32 | x64
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError ({path to my project}\testing-stuff\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F ({path to my project}\testing-stuff\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E ({path to my project}\testing-stuff\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at {path to my project}\testing-stuff\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at {path to my project}\testing-stuff\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at {path to my project}\testing-stuff\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:196:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError ({path to my project}\testing-stuff\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F ({path to my project}\testing-stuff\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E ({path to my project}\testing-stuff\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at {path to my project}\testing-stuff\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at {path to my project}\testing-stuff\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at {path to my project}\testing-stuff\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:196:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` succeeded python C:\Python39\python.EXE
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: C:\Python39\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                       ^
npm ERR! gyp ERR! stack SyntaxError: invalid syntax
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:326:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:378:20)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! gyp ERR! System Windows_NT 10.0.19042
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "{path to my project}\\testing-stuff\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd {path to my project}\testing-stuff\node_modules\node-sass
npm ERR! gyp ERR! node -v v15.9.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     {my user directory}\AppData\Local\npm-cache\_logs\2021-03-01T11_09_24_387Z-debug.log
```

**Comment by sugoidesune** [comment]
Wow. Turns out `scss-to-json` uses `node-sass` which uses `node-gyp` which has a PYTHON dependency?! What a bummer.
It has always worked out of the box for me, without ever thinking about Python.
Here's a codesandbox that also works right away with `nuxt-scss-to-js`
https://codesandbox.io/s/nuxt-scss-js-example-0r3tm?file=/assets/scss/variables.scss

I started using python on a separate project now and I still didn't receive any errors.

Just out of curiosity, did you manually install a global python and are you running windows 10?
You can try the following to fix the node-gyp issue: https://github.com/nodejs/node-gyp/issues/629#issuecomment-153196245

Indeed it looks like node-gyp print statement is using a 2.7 syntax, and that doesn't work with your 3.9 version.
I can recommend using a version manager for python https://pypi.org/project/pyenv-win/

I will look into using a different dependency that doesn't bite itself with python, but `node-sass` seems to be very prevalent in all libraries that work with sass in node.
